[project]
name = "agro-dash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.1",
    "gunicorn>=23.0.0",
    "pillow>=12.1.0",
    "python-decouple>=3.8",
    "whitenoise>=6.0.0",
]
